# Generated by Django 3.1.2 on 2021-05-25 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255, unique=True)),
                ('ntn', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('no_of_days', models.IntegerField(default=0)),
                ('bidding_amount', models.IntegerField(default=0)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, null=True, region=None)),
                ('tenderId', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('file_uploaded', models.FileField(default='', upload_to='uploads')),
                ('postedBy', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Construction', max_length=100)),
                ('organization_name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('availibility', models.CharField(default='active', max_length=10)),
                ('region', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, null=True, region=None)),
                ('opening_date', models.DateField(default='')),
                ('last_date', models.DateField(default='')),
                ('datepublished', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(default='', max_length=255)),
                ('file_uploaded', models.FileField(default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
